# Generated by Django 3.2.4 on 2021-06-05 00:36

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'data.json'
def load_data(apps, schema_editor):
    Centre = apps.get_model('centres', 'Centre')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            name = obj.get('name','no-name')
            district = obj.get('district','no-district')
            longitude = obj.get('lon', 0)
            latitude = obj.get('lat', 0)
            location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
            Centre(name=name, district=district, location = location).save()



class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
