# Generated by Django 3.2.4 on 2021-06-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0005_rename_street_address_testcentre_address'),
    ]

    operations = [
        
    ]
