# Generated by Django 3.2.4 on 2021-06-26 03:24

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'test_centres_data.json'
def load_data(apps, schema_editor):
    Centre = apps.get_model('centres', 'TestCentre')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects:
            name = obj.get('name','no-name')
            district = obj.get('district','no-district')
            address = obj.get('address','')
            contact = obj.get('contact','')
            fee = obj.get('fee','')
            longitude = obj.get('lon', 0)
            latitude = obj.get('lat', 0)
            location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
            Centre(name=name, district=district, address=address, contact=contact, fee=fee, location = location).save()

class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0005_rename_street_address_testcentre_address'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
